baseURL = 'http://j3ff.com/'
languageCode = 'en-us'
title = "j3ff.com"

DefaultContentLanguage = "en"

[params]
mainSections = [
    "post",
    "blog",
]


[params.sidebar]
subtitle = "A posting once a decade!"

[params.sidebar.avatar]
enabled = true
local = true
src = "img/avatar.jpg"

[[params.widgets.page]]
type = "toc"


[module]
[[module.mounts]]
  source = 'content'
  target = 'content'
  excludeFiles = [ '**/.DS_Store' ]

